# @ai-generated: true
# @ai-tool: Copilot
name: Workflow Lint (actionlint)

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    paths:
      - '.github/workflows/**'

permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Install actionlint (pinned)
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s 1.7.1
      - name: Run actionlint
        shell: bash
        run: ./actionlint -shellcheck=shellcheck
